insert into Aeroport(id_aero,nom_aero) values('CATL','ATLANTA');
                    insert into Aeroport(id_aero,nom_aero) values('CLAX','LOS ANGELES');
                    insert into Aeroport(id_aero,nom_aero) values('CIST','ISTANBUL');
                    insert into Aeroport(id_aero,nom_aero) values('CANC','ANCHORAGE');
                    insert into Aeroport(id_aero,nom_aero) values('CMAD','MADRID');
                    insert into Aeroport(id_aero,nom_aero) values('CPHX','PHOENIX');
                    insert into Aeroport(id_aero,nom_aero) values('CBCN','BARCELONA');
                    insert into Aeroport(id_aero,nom_aero) values('CSIA','XI AN');
                    insert into Aeroport(id_aero,nom_aero) values('CSZX','SHENZHEN');
                    insert into Aeroport(id_aero,nom_aero) values('CMAN','MANCHESTER');
                    insert into Aeroport(id_aero,nom_aero) values('CBJS','BEIJING');
                    insert into Aeroport(id_aero,nom_aero) values('CMEX','MEXICO CITY');
                    insert into Aeroport(id_aero,nom_aero) values('CBKK','BANGKOK');
                    insert into Aeroport(id_aero,nom_aero) values('CMAD','MADRID');
                    insert into Aeroport(id_aero,nom_aero) values('CCAN','GUANGZHOU');
                    insert into Aeroport(id_aero,nom_aero) values('CBOM','MUMBAI');
                    insert into Aeroport(id_aero,nom_aero) values('CBCN','BARCELONA');
                    insert into Aeroport(id_aero,nom_aero) values('CBOS','BOSTON');
                    insert into Aeroport(id_aero,nom_aero) values('CBER','BERLIN');
                    insert into Aeroport(id_aero,nom_aero) values('CSZX','SHENZHEN');
                    insert into Aeroport(id_aero,nom_aero) values('CCHI','CHICAGO');
                    insert into Aeroport(id_aero,nom_aero) values('CLAX','LOS ANGELES');
                    insert into Aeroport(id_aero,nom_aero) values('CBJS','BEIJING');
                    insert into Aeroport(id_aero,nom_aero) values('CDEN','DENVER');
                    insert into Aeroport(id_aero,nom_aero) values('CMEX','MEXICO CITY');
                    insert into Aeroport(id_aero,nom_aero) values('CSFO','SAN FRANCISCO');
                    insert into Aeroport(id_aero,nom_aero) values('CCLT','CHARLOTTE');
                    insert into Aeroport(id_aero,nom_aero) values('CCAN','GUANGZHOU');
                    insert into Aeroport(id_aero,nom_aero) values('CBOM','MUMBAI');
                    insert into Aeroport(id_aero,nom_aero) values('CKMG','KUNMING');
                    insert into Aeroport(id_aero,nom_aero) values('CWAS','WASHINGTON');
                    insert into Aeroport(id_aero,nom_aero) values('CDFW','DALLAS');
                    insert into Aeroport(id_aero,nom_aero) values('CDEN','DENVER');
                    insert into Aeroport(id_aero,nom_aero) values('CFRA','FRANKFURT');
                    insert into Aeroport(id_aero,nom_aero) values('CDEL','DELHI');
                    insert into Aeroport(id_aero,nom_aero) values('CCLT','CHARLOTTE');
                    insert into Aeroport(id_aero,nom_aero) values('CMUC','MUNICH');
                    insert into Aeroport(id_aero,nom_aero) values('CDTT','DETROIT');
                    insert into Aeroport(id_aero,nom_aero) values('CBER','BERLIN');
                    insert into Aeroport(id_aero,nom_aero) values('CPMI','PALMA DE MALLORCA');
                    insert into Aeroport(id_aero,nom_aero) values('CMAD','MADRID');
                    insert into Aeroport(id_aero,nom_aero) values('CORL','ORLANDO');
                    insert into Aeroport(id_aero,nom_aero) values('CBCN','BARCELONA');
                    insert into Aeroport(id_aero,nom_aero) values('CBOS','BOSTON');
                    insert into Aeroport(id_aero,nom_aero) values('CPMI','PALMA DE MALLORCA');
                    insert into Aeroport(id_aero,nom_aero) values('CAGP','MALAGA');
                    insert into Aeroport(id_aero,nom_aero) values('CANK','ANKARA');
                    insert into Aeroport(id_aero,nom_aero) values('CTCI','TENERIFE');
                    insert into Aeroport(id_aero,nom_aero) values('CEDI','EDINBURGH');
                    insert into Aeroport(id_aero,nom_aero) values('CLPA','GRAN CANARIA');
                    insert into Aeroport(id_aero,nom_aero) values('CPAR','PARIS');
                    insert into Aeroport(id_aero,nom_aero) values('CDFW','DALLAS');
                    insert into Aeroport(id_aero,nom_aero) values('CFRA','FRANKFURT');
                    insert into Aeroport(id_aero,nom_aero) values('CSFO','SAN FRANCISCO');
                    insert into Aeroport(id_aero,nom_aero) values('CMIA','MIAMI');
                    insert into Aeroport(id_aero,nom_aero) values('CORL','ORLANDO');
                    insert into Aeroport(id_aero,nom_aero) values('CFLL','FT LAUDERDALE');
                    insert into Aeroport(id_aero,nom_aero) values('CFAI','FAIRBANKS');
                    insert into Aeroport(id_aero,nom_aero) values('CTPA','TAMPA');
                    insert into Aeroport(id_aero,nom_aero) values('CNCE','NICE');
                    insert into Aeroport(id_aero,nom_aero) values('CLON','LONDON');
                    insert into Aeroport(id_aero,nom_aero) values('CATL','ATLANTA');
                    insert into Aeroport(id_aero,nom_aero) values('CDEL','DELHI');
                    insert into Aeroport(id_aero,nom_aero) values('CCAN','GUANGZHOU');
                    insert into Aeroport(id_aero,nom_aero) values('CMAN','MANCHESTER');
                    insert into Aeroport(id_aero,nom_aero) values('CXMN','XIAMEN');
                    insert into Aeroport(id_aero,nom_aero) values('CHYD','HYDERABAD');
                    insert into Aeroport(id_aero,nom_aero) values('CGDL','GUADALAJARA');
                    insert into Aeroport(id_aero,nom_aero) values('CBHX','BIRMINGHAM');
                    insert into Aeroport(id_aero,nom_aero) values('CEDI','EDINBURGH');
                    insert into Aeroport(id_aero,nom_aero) values('CATL','ATLANTA');
                    insert into Aeroport(id_aero,nom_aero) values('CPHX','PHOENIX');
                    insert into Aeroport(id_aero,nom_aero) values('CLAS','LAS VEGAS');
                    insert into Aeroport(id_aero,nom_aero) values('CSHA','SHANGHAI');
                    insert into Aeroport(id_aero,nom_aero) values('CHNL','HONOLULU');
                    insert into Aeroport(id_aero,nom_aero) values('CHGH','HANGZHOU');
                    insert into Aeroport(id_aero,nom_aero) values('CHAM','HAMBURG');
                    insert into Aeroport(id_aero,nom_aero) values('CCSX','CHANGSHA');
                    insert into Aeroport(id_aero,nom_aero) values('CHYD','HYDERABAD');
                    insert into Aeroport(id_aero,nom_aero) values('CGDL','GUADALAJARA');
                    insert into Aeroport(id_aero,nom_aero) values('CCHI','CHICAGO');
                    insert into Aeroport(id_aero,nom_aero) values('CATL','ATLANTA');
                    insert into Aeroport(id_aero,nom_aero) values('CLAX','LOS ANGELES');
                    insert into Aeroport(id_aero,nom_aero) values('CIST','ISTANBUL');
                    insert into Aeroport(id_aero,nom_aero) values('CSEA','SEATTLE');
                    insert into Aeroport(id_aero,nom_aero) values('CDFW','DALLAS');
                    insert into Aeroport(id_aero,nom_aero) values('CDEN','DENVER');
                    insert into Aeroport(id_aero,nom_aero) values('CFRA','FRANKFURT');
                    insert into Aeroport(id_aero,nom_aero) values('CMEX','MEXICO CITY');
                    insert into Aeroport(id_aero,nom_aero) values('CANC','ANCHORAGE');
                    insert into Aeroport(id_aero,nom_aero) values('CATL','ATLANTA');
                    insert into Aeroport(id_aero,nom_aero) values('CMEX','MEXICO CITY');
                    insert into Aeroport(id_aero,nom_aero) values('CCKG','CHONGQING');
                    insert into Aeroport(id_aero,nom_aero) values('CTAO','QINGDAO');
                    insert into Aeroport(id_aero,nom_aero) values('CSJC','SAN JOSE');
                    insert into Aeroport(id_aero,nom_aero) values('CJNU','JUNEAU');
                    insert into Aeroport(id_aero,nom_aero) values('CSNA','SANTA ANA');
                    insert into Aeroport(id_aero,nom_aero) values('CTNA','JINAN');
                    insert into Aeroport(id_aero,nom_aero) values('CCMH','COLUMBUS');
                    insert into Aeroport(id_aero,nom_aero) values('CSJD','SAN JOSE DEL CABO');
                    insert into Aeroport(id_aero,nom_aero) values('CKMG','KUNMING');
                    insert into Aeroport(id_aero,nom_aero) values('CHNL','HONOLULU');
                    insert into Aeroport(id_aero,nom_aero) values('CBLR','BENGALURU');
                    insert into Aeroport(id_aero,nom_aero) values('CCCU','KOLKATA');
                    insert into Aeroport(id_aero,nom_aero) values('CKWE','GUIYANG');
                    insert into Aeroport(id_aero,nom_aero) values('COTZ','KOTZEBUE');
                    insert into Aeroport(id_aero,nom_aero) values('CADQ','KODIAK');
                    insert into Aeroport(id_aero,nom_aero) values('COGG','KAHULUI');
                    insert into Aeroport(id_aero,nom_aero) values('CKTN','KETCHIKAN');
                    insert into Aeroport(id_aero,nom_aero) values('CCOK','KOCHI');
                    insert into Aeroport(id_aero,nom_aero) values('CLON','LONDON');
                    insert into Aeroport(id_aero,nom_aero) values('CLAX','LOS ANGELES');
                    insert into Aeroport(id_aero,nom_aero) values('CLAS','LAS VEGAS');
                    insert into Aeroport(id_aero,nom_aero) values('CBOS','BOSTON');
                    insert into Aeroport(id_aero,nom_aero) values('CFLL','FT LAUDERDALE');
                    insert into Aeroport(id_aero,nom_aero) values('CSLC','SALT LAKE CITY');
                    insert into Aeroport(id_aero,nom_aero) values('CSTL','ST LOUIS');
                    insert into Aeroport(id_aero,nom_aero) values('CNKG','NANJING');
                    insert into Aeroport(id_aero,nom_aero) values('CLPA','GRAN CANARIA');
                    insert into Aeroport(id_aero,nom_aero) values('CLYS','LYON');
                    insert into Aeroport(id_aero,nom_aero) values('CMEX','MEXICO CITY');
                    insert into Aeroport(id_aero,nom_aero) values('CMIA','MIAMI');
                    insert into Aeroport(id_aero,nom_aero) values('CMAD','MADRID');
                    insert into Aeroport(id_aero,nom_aero) values('CMSP','MINNEAPOLIS/ST PAUL');
                    insert into Aeroport(id_aero,nom_aero) values('CMUC','MUNICH');
                    insert into Aeroport(id_aero,nom_aero) values('CMIL','MILAN');
                    insert into Aeroport(id_aero,nom_aero) values('CBOM','MUMBAI');
                    insert into Aeroport(id_aero,nom_aero) values('CBOS','BOSTON');
                    insert into Aeroport(id_aero,nom_aero) values('CDTT','DETROIT');
                    insert into Aeroport(id_aero,nom_aero) values('CMAN','MANCHESTER');
                    insert into Aeroport(id_aero,nom_aero) values('CNYC','NEW YORK');
                    insert into Aeroport(id_aero,nom_aero) values('CCLT','CHARLOTTE');
                    insert into Aeroport(id_aero,nom_aero) values('CLAS','LAS VEGAS');
                    insert into Aeroport(id_aero,nom_aero) values('CNKG','NANJING');
                    insert into Aeroport(id_aero,nom_aero) values('CNCE','NICE');
                    insert into Aeroport(id_aero,nom_aero) values('CBNA','NASHVILLE');
                    insert into Aeroport(id_aero,nom_aero) values('CSJC','SAN JOSE');
                    insert into Aeroport(id_aero,nom_aero) values('CMSY','NEW ORLEANS');
                    insert into Aeroport(id_aero,nom_aero) values('COME','NOME');
                    insert into Aeroport(id_aero,nom_aero) values('CRDU','RALEIGH DURHAM');
                    insert into Aeroport(id_aero,nom_aero) values('CORL','ORLANDO');
                    insert into Aeroport(id_aero,nom_aero) values('CPDX','PORTLAND');
                    insert into Aeroport(id_aero,nom_aero) values('COAK','OAKLAND');
                    insert into Aeroport(id_aero,nom_aero) values('CMSY','NEW ORLEANS');
                    insert into Aeroport(id_aero,nom_aero) values('COME','NOME');
                    insert into Aeroport(id_aero,nom_aero) values('COTZ','KOTZEBUE');
                    insert into Aeroport(id_aero,nom_aero) values('CCLE','CLEVELAND');
                    insert into Aeroport(id_aero,nom_aero) values('COGG','KAHULUI');
                    insert into Aeroport(id_aero,nom_aero) values('CCMH','COLUMBUS');
                    insert into Aeroport(id_aero,nom_aero) values('CCVG','CINCINNATI');
                    insert into Aeroport(id_aero,nom_aero) values('CPAR','PARIS');
                    insert into Aeroport(id_aero,nom_aero) values('CPHX','PHOENIX');
                    insert into Aeroport(id_aero,nom_aero) values('CMSP','MINNEAPOLIS/ST PAUL');
                    insert into Aeroport(id_aero,nom_aero) values('CPHL','PHILADELPHIA');
                    insert into Aeroport(id_aero,nom_aero) values('CPMI','PALMA DE MALLORCA');
                    insert into Aeroport(id_aero,nom_aero) values('CPDX','PORTLAND');
                    insert into Aeroport(id_aero,nom_aero) values('CHKT','PHUKET');
                    insert into Aeroport(id_aero,nom_aero) values('CHOU','HOUSTON');
                    insert into Aeroport(id_aero,nom_aero) values('CSYX','SANYA');
                    insert into Aeroport(id_aero,nom_aero) values('CMRS','MARSEILLE');
                    insert into Aeroport(id_aero,nom_aero) values('CTAO','QINGDAO');
                    insert into Aeroport(id_aero,nom_aero) values('CJJN','QUANZHOU');
                    insert into Aeroport(id_aero,nom_aero) values('CKWN','QUINHAGAK');
                    insert into Aeroport(id_aero,nom_aero) values('CQRO','QUERETARO');
                    insert into Aeroport(id_aero,nom_aero) values('CMLI','MOLINE');
                    insert into Aeroport(id_aero,nom_aero) values('CJNG','JINING');
                    insert into Aeroport(id_aero,nom_aero) values('CBAR','QIONGHAI');
                    insert into Aeroport(id_aero,nom_aero) values('CBPE','QINHUANGDAO');
                    insert into Aeroport(id_aero,nom_aero) values('CXIC','XICHANG');
                    insert into Aeroport(id_aero,nom_aero) values('CIQN','QINGYANG');
                    insert into Aeroport(id_aero,nom_aero) values('CROM','ROME');
                    insert into Aeroport(id_aero,nom_aero) values('CLAS','LAS VEGAS');
                    insert into Aeroport(id_aero,nom_aero) values('CHYD','HYDERABAD');
                    insert into Aeroport(id_aero,nom_aero) values('CRDU','RALEIGH DURHAM');
                    insert into Aeroport(id_aero,nom_aero) values('COTZ','KOTZEBUE');
                    insert into Aeroport(id_aero,nom_aero) values('CTIJ','TIJUANA');
                    insert into Aeroport(id_aero,nom_aero) values('CBRW','BARROW');
                    insert into Aeroport(id_aero,nom_aero) values('CPMO','PALERMO');
                    insert into Aeroport(id_aero,nom_aero) values('COKC','OKLAHOMA CITY');
                    insert into Aeroport(id_aero,nom_aero) values('CRNO','RENO');
                    insert into Aeroport(id_aero,nom_aero) values('CIST','ISTANBUL');
                    insert into Aeroport(id_aero,nom_aero) values('CSEA','SEATTLE');
                    insert into Aeroport(id_aero,nom_aero) values('CDFW','DALLAS');
                    insert into Aeroport(id_aero,nom_aero) values('CANC','ANCHORAGE');
                    insert into Aeroport(id_aero,nom_aero) values('CBKK','BANGKOK');
                    insert into Aeroport(id_aero,nom_aero) values('CAYT','ANTALYA');
                    insert into Aeroport(id_aero,nom_aero) values('CTPA','TAMPA');
                    insert into Aeroport(id_aero,nom_aero) values('CWUH','WUHAN');
                    insert into Aeroport(id_aero,nom_aero) values('CMAA','CHENNAI');
                    insert into Aeroport(id_aero,nom_aero) values('CHYD','HYDERABAD');
                    insert into Aeroport(id_aero,nom_aero) values('CNYC','NEW YORK');
                    insert into Aeroport(id_aero,nom_aero) values('CCHI','CHICAGO');
                    insert into Aeroport(id_aero,nom_aero) values('CATL','ATLANTA');
                    insert into Aeroport(id_aero,nom_aero) values('CLAX','LOS ANGELES');
                    insert into Aeroport(id_aero,nom_aero) values('CWAS','WASHINGTON');
                    insert into Aeroport(id_aero,nom_aero) values('CSEA','SEATTLE');
                    insert into Aeroport(id_aero,nom_aero) values('CDFW','DALLAS');
                    insert into Aeroport(id_aero,nom_aero) values('CDEN','DENVER');
                    insert into Aeroport(id_aero,nom_aero) values('CANC','ANCHORAGE');
                    insert into Aeroport(id_aero,nom_aero) values('CSFO','SAN FRANCISCO');
                    insert into Aeroport(id_aero,nom_aero) values('CWAS','WASHINGTON');
                    insert into Aeroport(id_aero,nom_aero) values('CSEA','SEATTLE');
                    insert into Aeroport(id_aero,nom_aero) values('CDFW','DALLAS');
                    insert into Aeroport(id_aero,nom_aero) values('CCCU','KOLKATA');
                    insert into Aeroport(id_aero,nom_aero) values('CWUH','WUHAN');
                    insert into Aeroport(id_aero,nom_aero) values('CHOU','HOUSTON');
                    insert into Aeroport(id_aero,nom_aero) values('CSNA','SANTA ANA');
                    insert into Aeroport(id_aero,nom_aero) values('COTZ','KOTZEBUE');
                    insert into Aeroport(id_aero,nom_aero) values('CNNG','NANNING');
                    insert into Aeroport(id_aero,nom_aero) values('CTYN','TAIYUAN');
                    insert into Aeroport(id_aero,nom_aero) values('CSIA','XI AN');
                    insert into Aeroport(id_aero,nom_aero) values('CHGH','HANGZHOU');
                    insert into Aeroport(id_aero,nom_aero) values('CCGO','ZHENGZHOU');
                    insert into Aeroport(id_aero,nom_aero) values('CXMN','XIAMEN');
                    insert into Aeroport(id_aero,nom_aero) values('CHFE','HEFEI');
                    insert into Aeroport(id_aero,nom_aero) values('CXNN','XINING');
                    insert into Aeroport(id_aero,nom_aero) values('CJHG','JINGHONG');
                    insert into Aeroport(id_aero,nom_aero) values('CNTG','NANTONG');
                    insert into Aeroport(id_aero,nom_aero) values('CXUZ','XUZHOU');
                    insert into Aeroport(id_aero,nom_aero) values('COAX','OAXACA');
                    insert into Aeroport(id_aero,nom_aero) values('CNYC','NEW YORK');
                    insert into Aeroport(id_aero,nom_aero) values('CSJC','SAN JOSE');
                    insert into Aeroport(id_aero,nom_aero) values('CTNA','JINAN');
                    insert into Aeroport(id_aero,nom_aero) values('CWNZ','WENZHOU');
                    insert into Aeroport(id_aero,nom_aero) values('CINC','YINCHUAN');
                    insert into Aeroport(id_aero,nom_aero) values('CYNT','YANTAI');
                    insert into Aeroport(id_aero,nom_aero) values('CHDY','HAT YAI');
                    insert into Aeroport(id_aero,nom_aero) values('CFYU','FORT YUKON');
                    insert into Aeroport(id_aero,nom_aero) values('CFAT','FRESNO');
                    insert into Aeroport(id_aero,nom_aero) values('CYTY','YANGZHOU');
                    insert into Aeroport(id_aero,nom_aero) values('CCGO','ZHENGZHOU');
                    insert into Aeroport(id_aero,nom_aero) values('CDLC','DALIAN');
                    insert into Aeroport(id_aero,nom_aero) values('CLHW','LANZHOU');
                    insert into Aeroport(id_aero,nom_aero) values('CSJW','SHIJIAZHUANG');
                    insert into Aeroport(id_aero,nom_aero) values('CZUH','ZHUHAI');
                    insert into Aeroport(id_aero,nom_aero) values('CDYG','ZHANGJIAJIE');
                    insert into Aeroport(id_aero,nom_aero) values('CZHA','ZHANJIANG');
                    insert into Aeroport(id_aero,nom_aero) values('CZIH','IXTAPA ZIHUATANEJO');
                    insert into Aeroport(id_aero,nom_aero) values('CZYI','ZUNYI');
                    insert into Aeroport(id_aero,nom_aero) values('CHSN','ZHOUSHAN');
                    