# Generated by Django 4.2 on 2023-05-22 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0012_auto_20190502_0033"),
    ]

    operations = [
        migrations.CreateModel(
            name="aeroport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomAeroport", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomComplet", models.CharField(max_length=200)),
                ("telephone", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("adresse", models.CharField(max_length=200)),
                ("dernierTicketAchete", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="compagnie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomCompagnie", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="passager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomPassager", models.CharField(max_length=200)),
                ("telephone", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=50)),
                ("typePassager", models.CharField(max_length=200)),
                ("numeroCarte", models.CharField(max_length=200)),
                ("Pointage", models.IntegerField()),
                ("estblackliste", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="typeOffre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("typeofr", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ville",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomVille", models.CharField(max_length=200)),
                ("pays", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="volGenerique",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compagnie", models.CharField(max_length=200)),
                ("heureDepart", models.DateField()),
                ("heureArrivee", models.DateField()),
                ("capacite", models.IntegerField()),
                ("aeroportDepart", models.CharField(max_length=200)),
                ("aeroportArrivee", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="vol",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=200)),
                ("achatInstantane", models.BooleanField()),
                ("allerSimple", models.BooleanField()),
                ("dernierAchat", models.DateField()),
                ("nombreSiegeReserve", models.IntegerField()),
                ("dateDepart", models.DateField()),
                ("dateArrivee", models.DateField()),
                (
                    "typevol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.typeoffre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="reservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateReservation", models.DateField()),
                ("prixReservation", models.IntegerField()),
                ("devise", models.CharField(max_length=200)),
                ("montantTotal", models.IntegerField()),
                ("bagageInclus", models.BooleanField()),
                (
                    "nomPassager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.passager"
                    ),
                ),
                (
                    "nomclient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.client"
                    ),
                ),
                (
                    "nomvol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.vol"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="escale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lieuArret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.aeroport"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aeroport",
            name="paysAeroport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hotel.ville"
            ),
        ),
    ]
