# Generated by Django 4.2 on 2023-05-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0013_aeroport_client_compagnie_passager_typeoffre_ville_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="expertize",
        ),
        migrations.DeleteModel(
            name="Faq",
        ),
        migrations.DeleteModel(
            name="Gallery",
        ),
        migrations.RemoveField(
            model_name="service",
            name="items",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Expertize",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
