# Generated by Django 4.1.1 on 2023-06-08 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0014_remove_doctor_expertize_delete_faq_delete_gallery_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aeroport",
            name="paysAeroport",
        ),
        migrations.DeleteModel(
            name="compagnie",
        ),
        migrations.RemoveField(
            model_name="escale",
            name="lieuArret",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="nomPassager",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="nomclient",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="nomvol",
        ),
        migrations.DeleteModel(
            name="Slider",
        ),
        migrations.RemoveField(
            model_name="vol",
            name="typevol",
        ),
        migrations.DeleteModel(
            name="volGenerique",
        ),
        migrations.DeleteModel(
            name="aeroport",
        ),
        migrations.DeleteModel(
            name="client",
        ),
        migrations.DeleteModel(
            name="escale",
        ),
        migrations.DeleteModel(
            name="passager",
        ),
        migrations.DeleteModel(
            name="reservation",
        ),
        migrations.DeleteModel(
            name="typeOffre",
        ),
        migrations.DeleteModel(
            name="ville",
        ),
        migrations.DeleteModel(
            name="vol",
        ),
    ]
